accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp import views
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('success/', views.success, name='success'),
    path('main/', views.main, name='main'),
]

followapp/urls.py
from django.urls import path
from followapp.views import FollowView, FollowListView


app_name = "followapp"


urlpatterns = [
    path('follow/', FollowView.as_view(), name='follow'),
    path('list/', FollowListView.as_view(), name='list'),
]

profileapp/urls.py
from django.urls import path
from profileapp import views
from profileapp.views import ProfileCreateView, ProfileUpdateView


app_name = "profileapp"

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

snsProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from articleapp.views import ArticleListView
from snsProject import settings


urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribes/', include('subscribeapp.urls')),
    path('follows/', include('followapp.urls')),
    path('searchs/', include('searchapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountapp/models.py
from django.db import models

# Create your models here.

articleapp/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='project', null=True)
    other = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='follow', null=True)
    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    dislike_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='dislike_articles')

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import EmailField


class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].disabled = True

    email = EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(AccountUpdateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class AccountCreationForm(UserCreationForm):
    email = EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(AccountCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

accountapp/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin
from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm, AccountCreationForm
from articleapp.models import Article
from followapp.models import Follow


has_decorator = [login_required, account_ownership_required]


class AccountCreateView(CreateView):
    model = User
    form_class = AccountCreationForm
    success_url = reverse_lazy('articleapp:list')
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

    paginate_by = 25

    def get_context_data(self, **kwargs):
        other = self.object
        user = self.request.user

        if user.is_authenticated:
            follow = Follow.objects.filter(user=user, other=other)
        else:
            follow = None

        object_list = Article.objects.filter(writer=self.get_object())
        return super(AccountDetailView, self).get_context_data(object_list=object_list, follow=follow, **kwargs)


'''
@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
@method_decorator(account_ownership_required, 'get')
@method_decorator(account_ownership_required, 'post')
'''


@method_decorator(has_decorator, 'get')
@method_decorator(has_decorator, 'post')
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accountapp:main')
    template_name = 'accountapp/update.html'


'''
    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated and self.get_object() == self.request.user:
            return super().get(*args, **kwargs)
        else:
            return HttpResponseForbidden()

    def post(self, *args, **kwargs):
        if self.request.user.is_authenticated and self.get_object() == self.request.user:
            return super().get(*args, **kwargs)
        else:
            return HttpResponseForbidden()
'''


'''
@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
@method_decorator(account_ownership_required, 'get')
@method_decorator(account_ownership_required, 'post')
'''


@method_decorator(has_decorator, 'get')
@method_decorator(has_decorator, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'


'''
    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated and self.get_object() == self.request.user:
            return super().get(*args, **kwargs)
        else:
            return HttpResponseForbidden()

    def post(self, *args, **kwargs):
        if self.request.user.is_authenticated and self.get_object() == self.request.user:
            return super().get(*args, **kwargs)
        else:
            return HttpResponseForbidden()
'''


def success(request):
    return render(request, 'success.html')


@login_required
def main(request):
    return render(request, 'accountapp/main.html')


def logout_view(request):
    logout(request)
    return redirect('/')


'''
def main(request):
    if request.user.is_authenticated:
        return render(request, 'main.html')
    else:
        return HttpResponseRedirect(reverse('accountapp:login'))
'''

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block contents %}
<div style="text-align: center; max-width: 360px; margin: 1rem auto">
    <div style="font-size: 1.5rem; color: white; background-color: #b5c7ed;" class="btn btn-light btn-sm rounded-pill active px-4 mb-4">
        회원가입
    </div>
    <div>
        <form action="{% url 'accountapp:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <p></p>
            <input type="submit" value="확인" class="btn btn-secondary btn-sm active rounded-pill col-3 mt-3">
        </form>
    </div>
    <br><br><br><br><br><br><br><br>
</div>
{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% block contents %}
<div style="text-align: center; max-width: 500px; height: 53rem; margin: 4.5rem auto">
    <br>
    <div class="mb-4">
        <h6 style="font-size: .8rem; color: #565656"> 회원탈퇴를 원하시면 아래의 탈퇴버튼을 클릭하세요. </h6>
    </div>
    <div>
        <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            {{ form }}
            <p></p>
            <input type="submit" value="탈퇴" class="btn btn-danger btn-sm active rounded-pill col-3 mt-3">
        </form>
    </div>
</div>
{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block contents %}

<div style="text-align:center; max-width: 360px; margin: 1rem auto;">
    <p style="font-size: .8rem; color: #565656">
        {{ target_user.date_joined }}
    </p>
    {% if target_user.profile %}
    <img src="{{ target_user.profile.image.url }}" alt="" style="height: 8rem; width: 8rem; border-radius: 10rem; margin-bottom: .5rem; object-fit: cover;">
    <h5 style="font-size: .8rem; color: #565656">
        {{ target_user.profile.nickname }}
        {% if target_user.profile == user.profile %}
        <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}" style="text-decoration:none">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
              <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
              <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
            </svg>
        </a>
        {% endif %}
    </h5>
    <h6 style="font-size: .8rem; color: #262626">
        {{ target_user.profile.message }}
    </h6>
    {% else %}
    <img src="../../media/basic.jpg" alt="" style="height: 8rem; width: 8rem; border-radius: 10rem; margin-bottom: .5rem;">
    <a href="{% url 'profileapp:create' %}" style="text-decoration:none">
        <p>
            {% if target_user.pk == user.pk %}
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
              <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
              <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
            </svg>
            {%  endif %}
        </p>
    </a>
    {% endif %}

    {% if target_user == user %}
    <a href="{% url 'accountapp:update' pk=target_user.pk %}" title="회원수정" style="color: darkgreen; text-decoration: none;">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gear" viewBox="0 0 16 16">
          <path d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492zM5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0z"/>
          <path d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52l-.094-.319zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115l.094-.319z"/>
        </svg>
    </a>

    <a href="{% url 'accountapp:delete' pk=target_user.pk %}" title="회원탈퇴" style="color: darkred; text-decoration: none;">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle" viewBox="0 0 16 16">
          <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
          <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
        </svg>
    </a>
    {% endif %}
</div>

<div class="text-center" style="margin: 1rem;">
    {% if user.is_authenticated %}
        {% if target_user != user %}
            {% if not follow %}
            <a href="{% url 'followapp:follow' %}?account_pk={{ target_user.pk }}" style="background-color:#0095f6;" class="btn btn-primary btn-sm px-3">
                &nbsp팔로우&nbsp
            </a>
            {% else %}
            <a href="{% url 'followapp:follow' %}?account_pk={{ target_user.pk }}" class="btn btn-secondary btn-sm active px-4">
                팔로잉
            </a>
            {% endif %}
        {% endif %}
    {% endif %}
</div>

<div style="margin: 0rem; text-align: center">
    <div style="width: 5rem; max-width: 28%; height: auto; border: black; display: inline-block; vertical-align: middle">

        <p style="margin-bottom: 0; margin-top: 1rem; font-size: .9rem">게시글</p>
        <p style="vertical-align: middle; font-size: 1rem; color: #999">
            {{ object_list.count }}
        </p>
    </div>
    <div style="width: .05rem; height: 2rem; background-color: #979797;
    display: inline-block; vertical-align: middle"></div>
    <div style="width: 5rem; max-width: 28%; height: auto; border: black; display: inline-block; vertical-align: middle">

        <p style="margin-bottom: 0; margin-top: 1rem; font-size: .9rem">팔로워</p>
        <p style="vertical-align: middle; font-size: 1rem; color: #999">
            {{ target_user.follower.count }}
        </p>
    </div>
    <div style="width: .05rem; height: 2rem; background-color: #979797;
    display: inline-block; vertical-align: middle"></div>
    <div style="width: 5rem; max-width: 28%; height: auto; border: black; display: inline-block; vertical-align: middle">

        <p style="margin-bottom: 0; margin-top: 1rem; font-size: .9rem">팔로잉</p>
        <p style="vertical-align: middle; font-size: 1rem; color: #999">
            {{ target_user.following.count }}
        </p>
    </div>
    <div style="width: .05rem; height: 2rem; background-color: #979797;
    display: inline-block; vertical-align: middle"></div>
    <div style="width: 5rem; max-width: 28%; height: auto; border: black; display: inline-block; vertical-align: middle">

        <p style="margin-bottom: 0; margin-top: 1rem; font-size: .9rem">구독</p>
        <p style="vertical-align: middle; font-size: 1rem; color: #999">
            {{ target_user.subscription.count }}
        </p>
    </div>
</div>

<hr style="margin: 1.5rem;">

<div>
    {% include 'snippets/list_fragment.html' with article_list=object_list %}
</div>


{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block contents %}
<div style="text-align: center; max-width: 360px; margin: 1rem auto">
    <br>
    <div style="font-size: 1.5rem; color: white; background-color: #b5c7ed;" class="btn btn-light btn-sm rounded-pill active px-4 mb-4">
        로그인
    </div>
    <div>
        <form action="{% url 'accountapp:login' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
        <input type="submit" value="확인" class="btn btn-secondary btn-sm active rounded-pill col-5 mt-3">
        </form>
    </div>
    <br><br><br><br><br><br><br><br><br><br><br><br><br>
</div>
{% endblock %}

accountapp/templates/accountapp/main.html
{% extends 'base.html' %}

{% block contents %}
<div>
    <div style="text-align:center">
        <p>
            <h1>메인화면</h1>
        </p>
    </div>
</div>
{% endblock %}

accountapp/templates/accountapp/success.html
{% extends 'base.html' %}

{% block contents %}
<div>
    <div style="text-align:center">
        <p>
            <h1>메인화면(로그인)</h1>
        </p>
    </div>
</div>
{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block contents %}
<div style="text-align: center; max-width: 360px; height: 60rem; margin: 1rem auto">
    <div style="font-size: 1.5rem; color: white; background-color: #b5c7ed;" class="btn btn-light btn-sm rounded-pill active px-4 mb-4">
        회원수정
    </div>
<div style="text-align:center">
    <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <p></p>
        <input type="submit" value="확인" class="btn btn-secondary btn-sm active rounded-pill col-3 mt-3">
    </form>
</div>
</div>
{% endblock %}