followapp/urls.py
from django.urls import path
from followapp.views import FollowView, FollowListView


app_name = "followapp"


urlpatterns = [
    path('follow/', FollowView.as_view(), name='follow'),
    path('list/', FollowListView.as_view(), name='list'),
]

projectapp/urls.py
from django.urls import path
from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView


app_name = "projectapp"


urlpatterns = [
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    path('list/', ProjectListView.as_view(), name='list'),
]

snsProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from articleapp.views import ArticleListView
from snsProject import settings


urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribes/', include('subscribeapp.urls')),
    path('follows/', include('followapp.urls')),
    path('searchs/', include('searchapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subscribeapp/urls.py
from django.urls import path
from subscribeapp.views import SubscriptionView, SubscriptionListView


app_name = "subscribeapp"

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

articleapp/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='project', null=True)
    other = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='follow', null=True)
    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    dislike_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='dislike_articles')

projectapp/models.py
from django.db import models


class Project(models.Model):
    image = models.ImageField(upload_to='project/', null=False)
    title = models.CharField(max_length=20, null=True)
    description = models.CharField(max_length=200, null=True)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.pk} : {self.title}'

projectapp/forms.py
from django.forms import ModelForm
from projectapp.models import Project


class ProjectCreationForm(ModelForm):
    class Meta:
        model = Project
        fields = ['image', 'title', 'description']

projectapp/views.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, ListView
from django.views.generic.list import MultipleObjectMixin
from articleapp.models import Article
from projectapp.forms import ProjectCreationForm
from projectapp.models import Project
from subscribeapp.models import Subscription


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ProjectCreateView(CreateView):
    model = Project
    form_class = ProjectCreationForm
    template_name = 'projectapp/create.html'

    def get_success_url(self):
        return reverse_lazy('projectapp:detail', kwargs={'pk': self.object.pk})


class ProjectDetailView(DetailView, MultipleObjectMixin):
    model = Project
    context_object_name = 'target_project'
    template_name = 'projectapp/detail.html'
    paginate_by = 25

    def get_context_data(self, **kwargs):
        project = self.object
        user = self.request.user

        if user.is_authenticated:
            subscription = Subscription.objects.filter(user=user, project=project)
        else:
            subscription = None

        object_list = Article.objects.filter(project=self.get_object())
        return super(ProjectDetailView, self).get_context_data(object_list=object_list, subscription=subscription, **kwargs)


class ProjectListView(ListView, MultipleObjectMixin):
    model = Project
    context_object_name = 'project_list'
    template_name = 'projectapp/list.html'
    paginate_by = 15

projectapp/templates/projectapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block contents %}
<div style="text-align: center; max-width: 360px; height: 54rem; margin: 4rem auto">
    <div style="font-size: 1.5rem; color: white; background-color: #b5c7ed;" class="btn btn-light btn-sm rounded-pill active px-4 mb-4">
        프로젝트 생성
    </div>
    <div>
        <form action="{% url 'projectapp:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <p></p>
            <input type="submit" value="확인" class="btn btn-secondary btn-sm active rounded-pill col-3 mt-3">
        </form>
    </div>
</div>
{% endblock %}

projectapp/templates/projectapp/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block contents %}


<div style="text-align: center; max-width: 500px; margin: 1rem auto">
    <img src="{{ target_project.image.url }}" alt="" style="height: 10rem; width: 10rem; border-radius: 10rem; margin-bottom: .5rem; object-fit: cover;">
    <h6 style="font-size: .8rem; color: gray;">
        {{ target_project.created_at }}
    </h6>
    <h2 style="font-size: 2rem; margin: .6rem;">
        {{ target_project.title }}
    </h2>
    <h6 style="font-size: .9rem; color: gray; margin: -.3rem;">
        {{ target_project.description }}
    </h6>
</div>

<div class="text-center" style="margin: 1.5rem;">
    {% if user.is_authenticated %}
        {% if not subscription %}
        <a href="{% url 'subscribeapp:subscribe' %}?project_pk={{ target_project.pk }}" style="background-color:#cc0000;" class="btn btn-danger btn-sm px-4">
            &nbsp구독&nbsp
        </a>
        {% else %}
        <a href="{% url 'subscribeapp:subscribe' %}?project_pk={{ target_project.pk }}" class="btn btn-secondary btn-sm active px-4">
            구독중
        </a>
        {% endif %}
    {% endif %}
</div>

<div style="margin: 0rem; text-align: center">
    <div style="width: 5rem; max-width: 28%; height: auto; border: black; display: inline-block; vertical-align: middle">

        <p style="margin-bottom: 0; margin-top: 1rem; font-size: .9rem">게시글</p>
        <p style="vertical-align: middle; font-size: 1rem; color: #999">
            {{ object_list.count }}
        </p>
    </div>
    <div style="width: .05rem; height: 2rem; background-color: #979797;
    display: inline-block; vertical-align: middle"></div>
    <div style="width: 5rem; max-width: 28%; height: auto; border: black; display: inline-block; vertical-align: middle">

        <p style="margin-bottom: 0; margin-top: 1rem; font-size: .9rem">구독자</p>
        <p style="vertical-align: middle; font-size: 1rem; color: #999">
            {{ target_project.subscription.count }}
        </p>
    </div>
</div>

<hr style="margin: 1.5rem;">

<div style="margin-top: 2rem;">
    {% include 'snippets/list_fragment.html' with article_list=object_list %}
</div>


{% endblock %}

projectapp/templates/projectapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block contents %}

<style>
    .container {
        padding: 0;
        margin: 0, auto;
    }

    .container div {
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 1rem;
    }

    .container img {
        width: 7rem;
        height: 7rem;
        margin: .5rem;
        object-fit: cover;
        border-radius: 1rem;
    }
</style>

{% if project_list %}
<div class="container">
    {% for project in project_list %}
        <a href="{% url 'projectapp:detail' pk=project.pk %}" style="text-decoration: none; color: #565656;">
            {% include 'snippets/card_project.html' with project=project %}
        </a>
    {% endfor %}
</div>
<script src="{% static 'js/magicgrid.js' %}"></script>
{% else %}
<div style="text-align:center">
    <h4>No Articles YET!</h4>
</div>
{% endif %}

{% include 'snippets/pagination.html' with page_obj=page_obj %}

{%  if user.is_authenticated %}
<div style="text-align:center; position: sticky; bottom: 6rem; margin: 2rem;">
    <a href="{% url 'projectapp:create' %}" style="text-align:center; color: white; text-decoration: none;">
        <button style="background-color: #778899; color: white" class="btn btn-light btn-sm rounded-pill mt-3 px-3">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-richtext-fill" viewBox="0 0 16 16">
              <path d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0zM9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1zM7 6.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0zm-.861 1.542 1.33.886 1.854-1.855a.25.25 0 0 1 .289-.047l1.888.974V9.5a.5.5 0 0 1-.5.5H5a.5.5 0 0 1-.5-.5V9s1.54-1.274 1.639-1.208zM5 11h6a.5.5 0 0 1 0 1H5a.5.5 0 0 1 0-1zm0 2h3a.5.5 0 0 1 0 1H5a.5.5 0 0 1 0-1z"/>
            </svg>
            Create Project
        </button>
    </a>
</div>
<p style="margin: 31.5rem"></p>
{% endif %}

{% endblock %}