accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp import views
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('success/', views.success, name='success'),
    path('main/', views.main, name='main'),
]

articleapp/urls.py
from django.urls import path
from articleapp import views
from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, \
    ArticleListView, ArticleListPopView, ArticleListOldView

app_name = "articleapp"

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('list/', ArticleListView.as_view(), name='list'),
    path('plist/', ArticleListPopView.as_view(), name='plist'),
    path('olist/', ArticleListOldView.as_view(), name='olist'),
    path('<int:pk>/like/', views.like, name='like'),
    path('<int:pk>/dislike/', views.dislike, name='dislike'),
]

followapp/urls.py
from django.urls import path
from followapp.views import FollowView, FollowListView


app_name = "followapp"


urlpatterns = [
    path('follow/', FollowView.as_view(), name='follow'),
    path('list/', FollowListView.as_view(), name='list'),
]

projectapp/urls.py
from django.urls import path
from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView


app_name = "projectapp"


urlpatterns = [
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    path('list/', ProjectListView.as_view(), name='list'),
]

snsProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from articleapp.views import ArticleListView
from snsProject import settings


urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribes/', include('subscribeapp.urls')),
    path('follows/', include('followapp.urls')),
    path('searchs/', include('searchapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subscribeapp/urls.py
from django.urls import path
from subscribeapp.views import SubscriptionView, SubscriptionListView


app_name = "subscribeapp"

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="background-color: #f7f9fa">
    {% include 'header.html' %}
    <p></p><br>
    {% block contents %}
    {% endblock %}

    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
{% if not user.is_authenticated %}
    <div style="text-align:center; position: fixed; bottom: 0; width: 100%; height: 10rem; background-color: #262626; opacity: 0.9;">
        <div style="font-size: .8rem; color: white;">
            <span>
                <h4 style="margin-top: 1em; color: white;"><img src="/media/dimigo.jpg">Dimigostargram</h4>
            </span>
            <span>
                <a href="{% url 'accountapp:login' %}?next={{ request.path }} " style="text-decoration:none; width:80px;" class="btn btn-primary btn-sm mt-3 mb-3">
                    로그인
                </a>
            </span>
            &nbsp
            <span>
                <a href="{% url 'accountapp:create' %}" style="text-decoration:none; width:80px;" class="btn btn-danger btn-sm mt-3 mb-3">
                    회원가입
                </a>
            </span>
            <br><br>
        </div>
    </div>
{% else %}
    <div style="text-align:center; position: relative; bottom: -5.6rem; width: 100%; background-color: #262626; opacity: 0.9;">
        <div style="font-size: .8rem; color: white;">
            <br>
            <span>공지사항&nbsp&nbsp&nbsp|&nbsp&nbsp&nbsp</span>
            <span>제휴문의&nbsp&nbsp&nbsp|&nbsp&nbsp&nbsp</span>
            <span>서비스 소개</span>
            <h6 style="margin-top: .7rem; color: white;"><img src="/media/dimigo.jpg">Dimigostargram</h6>
            <br>
        </div>
    </div>
{% endif %}

templates/head.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shirink-to-fit=no">
    <link rel="icon" href="/media/dimigo.jpg">
    <title>Dimigostargram</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <!-- 구글 폰트 -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap" rel="stylesheet">

    <!-- fontawesome -->
    <script src="https://kit.fontawesome.com/4c225d5ccc.js" crossorigin="anonymous"></script>
</head>

templates/header.html
<style>
.btn-secondary {
    background-color: #262626;
    border-color: #262626;
    color: #FFF; }

.btn-secondary:active:focus:visited:hover {
    border-color: #565656;
    background-color: #0095f6;
    color: #FFF;}
</style>

<div style="text-align:center; background-color: #262626; margin: -1rem opacity: 0.5;">
    <a href="{% url 'articleapp:list' %}" style="text-decoration:none" class="btn btn-secondary btn-sm col-.1 mt-3 mb-.1">
    <div style="font-family: 'Kaushan Script', cursive; color: #0095f6">
        <font style="font-size: 3.5rem">Dimigostargram</font>
    </div>
    </a>

    <div>
        <a href="{% url 'articleapp:list' %}" style="text-decoration:none" class="btn btn-secondary btn-sm col-.1 mt-3 mb-.1">
            <span>Home</span>
        </a>
        &nbsp
        <a href="{% url 'projectapp:list' %}" style="text-decoration:none" class="btn btn-secondary btn-sm col-.1 mt-3 mb-.1">
            <span>Project</span>
        </a>
        &nbsp
        <a href="{% url 'subscribeapp:list' %}" style="text-decoration:none" class="btn btn-secondary btn-sm col-.1 mt-3 mb-.1">
            <span>Subsciption</span>
        </a>
        &nbsp
        <a href="{% url 'followapp:list' %}" style="text-decoration:none" class="btn btn-secondary btn-sm col-.1 mt-3 mb-.1">
            <span>Following</span>
        </a>
        &nbsp
        {% if not user.is_authenticated %}
        <a href="{% url 'accountapp:login' %}?next={{ request.path }} " style="text-decoration:none" class="btn btn-secondary btn-sm col-.1 mt-3 mb-.1">
            <span>Login</span>
        </a>
        &nbsp
        <a href="{% url 'accountapp:create' %}" style="text-decoration:none" class="btn btn-secondary btn-sm col-.1 mt-3 mb-.1">
            <span>SignUp</span>
        </a>
        {% else %}
        <a href="{% url 'accountapp:detail' pk=user.pk %}" style="text-decoration:none" class="btn btn-secondary btn-sm col-.1 mt-3 mb-.1">
            <span>MyPage</span>
        </a>
        &nbsp
        <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" style="text-decoration:none" class="btn btn-secondary btn-sm col-.1 mt-3 mb-.1">
            <span>Logout</span>
        </a>
        {% endif %}
    </div>
</div>