accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp import views
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('success/', views.success, name='success'),
    path('main/', views.main, name='main'),
]

articleapp/urls.py
from django.urls import path
from articleapp import views
from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, \
    ArticleListView, ArticleListPopView, ArticleListOldView

app_name = "articleapp"

urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('list/', ArticleListView.as_view(), name='list'),
    path('plist/', ArticleListPopView.as_view(), name='plist'),
    path('olist/', ArticleListOldView.as_view(), name='olist'),
    path('<int:pk>/like/', views.like, name='like'),
    path('<int:pk>/dislike/', views.dislike, name='dislike'),
]

followapp/urls.py
from django.urls import path
from followapp.views import FollowView, FollowListView


app_name = "followapp"


urlpatterns = [
    path('follow/', FollowView.as_view(), name='follow'),
    path('list/', FollowListView.as_view(), name='list'),
]

searchapp/urls.py
from django.urls import path
from searchapp import views


app_name = "searchapp"


urlpatterns = [
    path('search/', views.search, name='search'),
]

snsProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from articleapp.views import ArticleListView
from snsProject import settings


urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribes/', include('subscribeapp.urls')),
    path('follows/', include('followapp.urls')),
    path('searchs/', include('searchapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleapp/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='project', null=True)
    other = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='follow', null=True)
    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    dislike_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='dislike_articles')

articleapp/forms.py
from django.forms import ModelForm
from articleapp.models import Article


class ArticleCreationForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'image', 'project', 'content']

articleapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.views.generic.edit import FormMixin
from django.views.generic.list import MultipleObjectMixin
from articleapp.decorators import article_ownership_required
from articleapp.forms import ArticleCreationForm
from articleapp.models import Article
from commentapp.forms import CommentCreationForm


has_decorator = [login_required, article_ownership_required]


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleCreationForm
    template_name = 'articleapp/create.html'

    def form_valid(self, form):
        temp_article = form.save(commit=False)
        temp_article.writer = self.request.user
        temp_article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('articleapp:detail', kwargs={'pk': self.object.pk})


class ArticleDetailView(DetailView, FormMixin):
    model = Article
    form_class = CommentCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'

    def get_success_url(self):
        return reverse_lazy('articleapp:detail', kwargs={'pk': self.object.pk})


@method_decorator(has_decorator, 'get')
@method_decorator(has_decorator, 'post')
class ArticleUpdateView(UpdateView):
    model = Article
    context_object_name = 'target_article'
    form_class = ArticleCreationForm
    template_name = 'articleapp/update.html'

    def get_success_url(self):
        return reverse_lazy('articleapp:detail', kwargs={'pk': self.object.pk})


@method_decorator(has_decorator, 'get')
@method_decorator(has_decorator, 'post')
class ArticleDeleteView(DeleteView):
    model = Article
    context_object_name = 'target_article'
    success_url = reverse_lazy('articleapp:list')
    template_name = 'articleapp/delete.html'


class ArticleListView(ListView, MultipleObjectMixin):
    queryset = Article.objects.order_by('-created_at')
    context_object_name = 'article_list'
    template_name = 'articleapp/list.html'
    paginate_by = 25


class ArticleListPopView(ListView, MultipleObjectMixin):
    queryset = Article.objects.order_by('-like_users', 'dislike_users')
    context_object_name = 'article_pop_list'
    template_name = 'articleapp/pop_list.html'
    paginate_by = 25


class ArticleListOldView(ListView, MultipleObjectMixin):
    queryset = Article.objects.order_by('created_at')
    context_object_name = 'article_old_list'
    template_name = 'articleapp/old_list.html'
    paginate_by = 25


def like(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.user in article.like_users.all():
        article.like_users.remove(request.user)
    else:
        article.like_users.add(request.user)
        article.dislike_users.remove(request.user)
    return redirect('articleapp:detail', article.pk)


def dislike(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.user in article.dislike_users.all():
        article.dislike_users.remove(request.user)
    else:
        article.dislike_users.add(request.user)
        article.like_users.remove(request.user)
    return redirect('articleapp:detail', article.pk)

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block contents %}
<div style="text-align: center; max-width: 360px; height: 60rem; margin: 1rem auto">
    <div style="font-size: 1.5rem; color: white; background-color: #b5c7ed;" class="btn btn-light btn-sm rounded-pill active px-4 mb-4">
        Article 생성
    </div>
    <div>
        <form action="{% url 'articleapp:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <p></p>
            <input type="submit" value="확인" class="btn btn-secondary btn-sm active rounded-pill col-4 mt-3">
        </form>
    </div>
</div>
{% endblock %}

articleapp/templates/articleapp/delete.html
{% extends 'base.html' %}

{% block contents %}
<div style="text-align: center; max-width: 500px; height: 60rem; margin: 1rem auto">
    <br>
    <div class="mb-4" style="font-size: .8rem; color: #565656">
        아래 제목의 article을 삭제합니다. 맞으면 삭제버튼을 클릭하세요.<br><br>
        <span style="background-color: black; font-size: 1.4rem; color: white">&nbsp&nbsp{{ target_article.title }}&nbsp&nbsp</span>
    </div>
    <br><br>
    <div>
        <form action="{% url 'articleapp:delete' pk=target_article.pk %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="삭제" class="btn btn-danger btn-sm active rounded-pill col-3 mt-1">
        </form>
    </div>
</div>
{% endblock %}

articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}

{% block contents %}

<style>
a:link {
  text-decoration: none;
}

a:visited {
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}

a:active {
  text-decoration: underline;
}
</style>

<div>
    <div style="text-align: center; max-width: 700px; margin: 0rem auto">
        <h2 style="font-size: 2rem;">
            {{ target_article.title }}
        </h2>
        <h6 style="font-size: .9rem;">
            <a href="{% url 'accountapp:detail' pk=target_article.writer.pk %}" style="color: gray;" >
                {{ target_article.writer.profile.nickname }}
            </a>
        </h6>
        <hr>
        <div style="text-align: center; font-size: .9rem; color: #565656; margin: -0.5rem auto">
            {{ target_article.created_at }}
        </div>
        <br>
        <img src="{{ target_article.image.url }}" style="width: 350px; cursor: pointer;" alt="" onclick="doImgPop('{{ target_article.image.url }}')">
        <p>
            <br><br>
            {{ target_article.content }}
        </p>

        <br><hr>

        <div style="margin: -.2rem;">
            {% if not user.is_authenticated %}
            <i class="far fa-thumbs-up fa-lg animated infinite bounce delay-1s" style="font-size: 1rem; color: gray;"></i>
            <span style="font-size: .9rem;">{{ target_article.like_users.count }}</span>
            &nbsp&nbsp
            <i class="far fa-thumbs-down fa-lg animated infinite bounce delay-1s" style="font-size: 1rem; color: gray;"></i>
            <span style="font-size: .9rem;">{{ target_article.dislike_users.count }}</span>
            {% else %}
            {% if request.user in target_article.like_users.all %}
            <a href="{% url 'articleapp:like' target_article.pk %}" style="text-decoration: none">
                <i class="far fa-thumbs-up fa-lg animated hinge delay-1s" style="font-size: 1rem; color: red;"></i>
            </a>
            <span style="font-size: .9rem;">{{ target_article.like_users.count }}</span>
            {% else %}
            <a href="{% url 'articleapp:like' target_article.pk %}" style="text-decoration: none">
                <i class="far fa-thumbs-up fa-lg animated infinite bounce delay-1s" style="font-size: 1rem; color: gray;"></i>
            </a>
            <span style="font-size: .9rem;">{{ target_article.like_users.count }}</span>
            {% endif %}

            &nbsp&nbsp&nbsp

            {% if request.user in target_article.dislike_users.all %}
            <a href="{% url 'articleapp:dislike' target_article.pk %}" style="text-decoration: none">
                <i class="far fa-thumbs-down fa-lg animated hinge delay-1s" style="font-size: 1rem; color: blue;"></i>
            </a>
            <span style="font-size: .9rem;">{{ target_article.dislike_users.count }}</span>
            {% else %}
            <a href="{% url 'articleapp:dislike' target_article.pk %}" style="text-decoration: none">
                <i class="far fa-thumbs-down fa-lg animated infinite bounce delay-1s" style="font-size: 1rem; color: gray;"></i>
            </a>
            <span style="font-size: .9rem;">{{ target_article.dislike_users.count }}</span>
            {% endif %}
            {% endif %}
        </div>

        {% if target_article.writer == user %}
        <a href="{% url 'articleapp:update' pk=target_article.pk %}" class="btn btn-primary btn-sm active col-1.5 mt-5 mb-3">
            Article 수정
        </a>
        <a href="{% url 'articleapp:delete' pk=target_article.pk %}" class="btn btn-danger btn-sm active col-1.5 mt-5 mb-3">
            Article 삭제
        </a>
        {% endif %}

        {% for comment in target_article.comment.all %}
        {% include 'commentapp/detail.html' with comment=comment %}
        {% endfor %}

        {% include 'commentapp/create.html' with article=target_article %}
    </div>
</div>

<script>
function doImgPop(img){
    img1= new Image();
    img1.src=(img);
    imgControll(img);
}

function imgControll(img){
    if((img1.width!=0)&&(img1.height!=0)){
        viewImage(img);
    }
    else{
        controller="imgControll('"+img+"')";
        intervalID=setTimeout(controller,20);
    }
}

function viewImage(img){
    W=img1.width;
    H=img1.height;
    O="width="+W+",height="+H+",scrollbars=no";
    imgWin=window.open("","",O);
    imgWin.document.write("<html><head><title>{{ target_article.title }}</title></head>");
    imgWin.document.write("<body topmargin=0 leftmargin=0></body>");
    imgWin.document.write("<img src="+img+" onclick='self.close()' style='cursor:pointer;' title ='클릭하시면 창이 닫힙니다.'>");
    imgWin.document.close();
}
</script>

{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block contents %}

<style>
    .container {
        padding: 0;
        margin: 0, auto;
    }

    .container a {
        width: 45%;
        max-width: 250px;
    }

    .container div {
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 1rem;
    }

    .container img {
        width: 100%;
        border-radius: 1rem;
    }


    .selectbox {
        position: relative;
        width: 90px;  /* 너비설정 */
        border: 1px solid #999;  /* 테두리 설정 */
        z-index: 1;
    }

    .selectbox:before {
        content: "";
        position: absolute;
        top: 50%;
        right: 15px;
        width: 0;
        height: 0;
        margin-top: -1px;
        border-left: 5px solid transparent;
        border-right: 5px solid transparent;
        border-top: 5px solid #333;
    }

    .selectbox label {
        position: absolute;
        top: 1px;  /* 위치정렬 */
        left: 5px;  /* 위치정렬 */
        padding: .1em .1em;  /* select의 여백 크기 만큼 */
        color: #999;
        z-index: -1;  /* IE8에서 label이 위치한 곳이 클릭되지 않는 것 해결 */
    }

    .selectbox select {
        width: 100%;
        height: auto;  /* 높이 초기화 */
        line-height: normal;  /* line-height 초기화 */
        font-family: inherit;  /* 폰트 상속 */
        padding: .1em .1em;  /* 여백과 높이 결정 */
        border: 0;
        opacity: 1;  /* 숨기기 */
        filter:alpha(opacity=0);  /* IE8 숨기기 */
        -webkit-appearance: none; /* 네이티브 외형 감추기 */
        -moz-appearance: none;
        appearance: none;
    }
</style>

<div style="position: relative; top: -1.5rem; opacity: 1;">
    <form class="form-inline my-2 my-lg-0" action="{% url 'searchapp:search' %}" method="get">
        {% csrf_token %}
        <nav class="navbar navbar-expand-sm bg-light">
            <input name="q" style="height: 30px" class="form-control mr-sm-2" type="text" placeholder="Search"> &nbsp&nbsp
            <button style="width: 50px" class="btn btn-success btn-sm active" type="submit">검색</button>
        </nav>
    </form>
    <div class="selectbox" style="position: relative; top: 2rem; left: 81%; opacity: .6; margin: -2rem;">
        <select id="select" onchange="this.options[this.selectedIndex].value && (window.location = this.options[this.selectedIndex].value);">
            <option value="{% url 'articleapp:list' %}">최신순</option>
            <option value="{% url 'articleapp:plist' %}">인기순</option>
            <option value="{% url 'articleapp:olist' %}">오래된순</option>
        </select>
    </div>
</div>

<br><br>

{% if article_list %}
<div class="container">
    {% for article in article_list %}
    <a href="{% url 'articleapp:detail' pk=article.pk %}">
        {% include 'snippets/card.html' with article=article %}
    </a>
    {% endfor %}
</div>
<script src="{% static 'js/magicgrid.js' %}"></script>
{% else %}
<div style="text-align:center">
    <h4>No Articles YET!</h4>
</div>
{% endif %}

{% include 'snippets/pagination.html' with page_obj=page_obj %}

{%  if user.is_authenticated %}
<div style="text-align:center; margin: 2rem;">
    <a href="{% url 'articleapp:create' %}" style="color: white; text-decoration: none;">
        <button style="background-color: #778899; color: white" class="btn btn-light btn-sm rounded-pill mt-3 px-3">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-images" viewBox="0 0 16 16">
              <path d="M4.502 9a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z"/>
              <path d="M14.002 13a2 2 0 0 1-2 2h-10a2 2 0 0 1-2-2V5A2 2 0 0 1 2 3a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v8a2 2 0 0 1-1.998 2zM14 2H4a1 1 0 0 0-1 1h9.002a2 2 0 0 1 2 2v7A1 1 0 0 0 15 11V3a1 1 0 0 0-1-1zM2.002 4a1 1 0 0 0-1 1v8l2.646-2.354a.5.5 0 0 1 .63-.062l2.66 1.773 3.71-3.71a.5.5 0 0 1 .577-.094l1.777 1.947V5a1 1 0 0 0-1-1h-10z"/>
            </svg>
            Create Article
        </button>
    </a>
</div>
{% endif %}

{% endblock %}

articleapp/templates/articleapp/old_list.html
{% extends 'base.html' %}
{% load static %}

{% block contents %}

<style>
    .container {
        padding: 0;
        margin: 0, auto;
    }

    .container a {
        width: 45%;
        max-width: 250px;
    }

    .container div {
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 1rem;
    }

    .container img {
        width: 100%;
        border-radius: 1rem;
    }

    .selectbox {
        position: relative;
        width: 90px;  /* 너비설정 */
        border: 1px solid #999;  /* 테두리 설정 */
        z-index: 1;
    }

    .selectbox:before {
        content: "";
        position: absolute;
        top: 50%;
        right: 15px;
        width: 0;
        height: 0;
        margin-top: -1px;
        border-left: 5px solid transparent;
        border-right: 5px solid transparent;
        border-top: 5px solid #333;
    }

    .selectbox label {
        position: absolute;
        top: 1px;  /* 위치정렬 */
        left: 5px;  /* 위치정렬 */
        padding: .1em .1em;  /* select의 여백 크기 만큼 */
        color: #999;
        z-index: -1;  /* IE8에서 label이 위치한 곳이 클릭되지 않는 것 해결 */
    }

    .selectbox select {
        width: 100%;
        height: auto;  /* 높이 초기화 */
        line-height: normal;  /* line-height 초기화 */
        font-family: inherit;  /* 폰트 상속 */
        padding: .1em .1em;  /* 여백과 높이 결정 */
        border: 0;
        opacity: 1;  /* 숨기기 */
        filter:alpha(opacity=0);  /* IE8 숨기기 */
        -webkit-appearance: none; /* 네이티브 외형 감추기 */
        -moz-appearance: none;
        appearance: none;
    }
</style>

<div style="width: 100%; position: relative; top: -1.5rem; opacity: 1;">
    <form class="form-inline my-2 my-lg-0" action="{% url 'searchapp:search' %}" method="get">
        {% csrf_token %}
        <nav class="navbar navbar-expand-sm bg-light">
            <input name="q" style="height: 30px" class="form-control mr-sm-2" type="text" placeholder="Search"> &nbsp&nbsp
            <button style="width: 50px" class="btn btn-success btn-sm active" type="submit">검색</button>
        </nav>
    </form>
    <div class="selectbox" style="position: relative; top: 2rem; left: 81%; opacity: .6; margin: -2rem;">
        <select id="select" onchange="this.options[this.selectedIndex].value && (window.location = this.options[this.selectedIndex].value);">
            <option value="{% url 'articleapp:olist' %}">오래된순</option>
            <option value="{% url 'articleapp:list' %}">최신순</option>
            <option value="{% url 'articleapp:plist' %}">인기순</option>
        </select>
    </div>
</div>

<br><br>

{% if article_old_list %}
<div class="container">
    {% for article in article_old_list %}
    <a href="{% url 'articleapp:detail' pk=article.pk %}">
        {% include 'snippets/card.html' with article=article %}
    </a>
    {% endfor %}
</div>
<script src="{% static 'js/magicgrid.js' %}"></script>
{% else %}
<div style="text-align:center">
    <h4>No Articles YET!</h4>
</div>
{% endif %}

{% include 'snippets/pagination.html' with page_obj=page_obj %}

{%  if user.is_authenticated %}
<div style="text-align:center; margin: 2rem;">
    <a href="{% url 'articleapp:create' %}" style="color: white; text-decoration: none;">
        <button style="background-color: #778899; color: white" class="btn btn-light btn-sm rounded-pill mt-3 px-3">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-images" viewBox="0 0 16 16">
              <path d="M4.502 9a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z"/>
              <path d="M14.002 13a2 2 0 0 1-2 2h-10a2 2 0 0 1-2-2V5A2 2 0 0 1 2 3a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v8a2 2 0 0 1-1.998 2zM14 2H4a1 1 0 0 0-1 1h9.002a2 2 0 0 1 2 2v7A1 1 0 0 0 15 11V3a1 1 0 0 0-1-1zM2.002 4a1 1 0 0 0-1 1v8l2.646-2.354a.5.5 0 0 1 .63-.062l2.66 1.773 3.71-3.71a.5.5 0 0 1 .577-.094l1.777 1.947V5a1 1 0 0 0-1-1h-10z"/>
            </svg>
            Create Article
        </button>
    </a>
</div>
{% endif %}

{% endblock %}

articleapp/templates/articleapp/pop_list.html
{% extends 'base.html' %}
{% load static %}

{% block contents %}

<style>
    .container {
        padding: 0;
        margin: 0, auto;
    }

    .container a {
        width: 45%;
        max-width: 250px;
    }

    .container div {
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 1rem;
    }

    .container img {
        width: 100%;
        border-radius: 1rem;
    }


    .selectbox {
        position: relative;
        width: 90px;  /* 너비설정 */
        border: 1px solid #999;  /* 테두리 설정 */
        z-index: 1;
    }

    .selectbox:before {
        content: "";
        position: absolute;
        top: 50%;
        right: 15px;
        width: 0;
        height: 0;
        margin-top: -1px;
        border-left: 5px solid transparent;
        border-right: 5px solid transparent;
        border-top: 5px solid #333;
    }

    .selectbox label {
        position: absolute;
        top: 1px;  /* 위치정렬 */
        left: 5px;  /* 위치정렬 */
        padding: .1em .1em;  /* select의 여백 크기 만큼 */
        color: #999;
        z-index: -1;  /* IE8에서 label이 위치한 곳이 클릭되지 않는 것 해결 */
    }

    .selectbox select {
        width: 100%;
        height: auto;  /* 높이 초기화 */
        line-height: normal;  /* line-height 초기화 */
        font-family: inherit;  /* 폰트 상속 */
        padding: .1em .1em;  /* 여백과 높이 결정 */
        border: 0;
        opacity: 1;  /* 숨기기 */
        filter:alpha(opacity=0);  /* IE8 숨기기 */
        -webkit-appearance: none; /* 네이티브 외형 감추기 */
        -moz-appearance: none;
        appearance: none;
    }
</style>

<div style=" position: relative; top: -1.5rem; opacity: 1;">
    <form class="form-inline my-2 my-lg-0" action="{% url 'searchapp:search' %}" method="get">
        {% csrf_token %}
        <nav class="navbar navbar-expand-sm bg-light">
            <input name="q" style="height: 30px" class="form-control mr-sm-2" type="text" placeholder="Search"> &nbsp&nbsp
            <button style="width: 50px" class="btn btn-success btn-sm active" type="submit">검색</button>
        </nav>
    </form>
    <div class="selectbox" style="position: relative; top: 2rem; left: 81%; opacity: .6; margin: -2rem;">
        <select id="select" onchange="this.options[this.selectedIndex].value && (window.location = this.options[this.selectedIndex].value);">
            <option value="{% url 'articleapp:plist' %}">인기순</option>
            <option value="{% url 'articleapp:list' %}">최신순</option>
            <option value="{% url 'articleapp:olist' %}">오래된순</option>
        </select>
    </div>
</div>

<br><br>

{% if article_pop_list %}
<div class="container">
    {% for article in article_pop_list %}
    <a href="{% url 'articleapp:detail' pk=article.pk %}">
        {% include 'snippets/card.html' with article=article %}
    </a>
    {% endfor %}
</div>
<script src="{% static 'js/magicgrid.js' %}"></script>
{% else %}
<div style="text-align:center">
    <h4>No Articles YET!</h4>
</div>
{% endif %}

{% include 'snippets/pagination.html' with page_obj=page_obj %}

{%  if user.is_authenticated %}
<div style="text-align:center; margin: 2rem;">
    <a href="{% url 'articleapp:create' %}" style="color: white; text-decoration: none;">
        <button style="background-color: #778899; color: white" class="btn btn-light btn-sm rounded-pill mt-3 px-3">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-images" viewBox="0 0 16 16">
              <path d="M4.502 9a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z"/>
              <path d="M14.002 13a2 2 0 0 1-2 2h-10a2 2 0 0 1-2-2V5A2 2 0 0 1 2 3a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v8a2 2 0 0 1-1.998 2zM14 2H4a1 1 0 0 0-1 1h9.002a2 2 0 0 1 2 2v7A1 1 0 0 0 15 11V3a1 1 0 0 0-1-1zM2.002 4a1 1 0 0 0-1 1v8l2.646-2.354a.5.5 0 0 1 .63-.062l2.66 1.773 3.71-3.71a.5.5 0 0 1 .577-.094l1.777 1.947V5a1 1 0 0 0-1-1h-10z"/>
            </svg>
            Create Article
        </button>
    </a>
</div>
{% endif %}

{% endblock %}

articleapp/templates/articleapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block contents %}
<div style="text-align: center; max-width: 360px; height: 60rem; margin: 1rem auto">
    <div style="font-size: 1.5rem; color: white; background-color: #b5c7ed;" class="btn btn-light btn-sm rounded-pill active px-4 mb-4">
        Article 수정
    </div>
    <div>
        <form action="{% url 'articleapp:update' pk=target_article.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <p></p>
            <input type="submit" value="확인" class="btn btn-secondary btn-sm active rounded-pill col-5 mt-3 mb-3">
        </form>
    </div>
</div>
{% endblock %}